spring.application.name: bff-service
server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    org.springframework:
      security: debug

feign:
  customer:
    service:
      url: ${CUSTOMER_SERVICE_URL}